---
- name: Ensure .ssh directory exists for pi user
  file: path=/home/pi/.ssh state=directory owner=pi group=pi mode=0700

- name: Generate authorized_keys for user pi
  template: dest=/home/pi/.ssh/authorized_keys src=authorized_keys.j2 owner=pi group=pi mode=0600
